version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - python/load-cache
     - run:
        name: install dependencies
          - python/install-deps
          - python/save-cache
     - run:
        name: run server
        command: python manage.py runserver 8000
        background: true

workflows:
  main:
    jobs:
      - build
