version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run: sudo chown -R $SUPER:$USER circleci:circleci /usr/local
      - run: sudo chown -R circleci:circleci /usr/local
      - run: sudo chown -R circleci:circleci /usr/local/bin
      - run: sudo chown -R circleci:circleci /usr/local/lib/python3.7/site-packages
      - python/load-cache
      - python/save-cache
      - run:
          name: pip upgrade
          command: pip install --user --upgrade pip
      - python/install-deps
      - run:
          name: run server
          command: |
            python manage.py runserver
          background: true
          ports: 
              - "8000"

workflows:
  main:
    jobs:
      - build
