version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - run:
          name: run server
          command: python manage.py runserver 8000
          background: true
      - python/save-cache

workflows:
  main:
    jobs:
      - build
