version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - python/load-cache
      - run:
          name: pip upgrade
          command: pip install --user --upgrade pip
      - python/install-deps
      - run:
          name: run server
          command: |
            gunicorn simplemooc.wsgi:application --bind=127.0.0.1:8000 --pid=gunicorn.txt --daemon
          background: true
      - python/save-cache

workflows:
  main:
    jobs:
      - build
