version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.7.3
        environment:
            PIPENV_VENV_IN_PROJECT: true
    steps:
      - checkout
      - python/load-cache
      - run:
          name: pip upgrade
          command: pip install --user --upgrade pip
      - python/install-deps
      - run:
          name: run server
          command: |
            python manage.py runserver
          background: true
          ports: 
              - "8000"
      - python/save-cache

workflows:
  main:
    jobs:
      - build
